# Generated by Django 4.2.6 on 2023-11-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_organization_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='fund_raised',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
