# Generated by Django 5.0 on 2023-12-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='organization',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
