# Generated by Django 5.0 on 2023-12-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='action',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
