# Generated by Django 5.0 on 2023-12-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
